<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
       <img src="EIA.png" />
        <p > </p>
        <p class="lead"></p>
        <p><a href="/Account/Login" class="btn btn-primary btn-lg">GET STARTED &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>WHAT IS ECO IMPACT AFRICA</h2>
            <p>
                is a startup organization with a strong commitment to environmental sustainability.  
                We are a renewable energy company committed to accelerating the global transition to a sustainable, 
                low carbon future. We offer a wide range of innovative and customized clean energy solutions designed to
                meet the unique needs of individuals and businesses. We are particularly interested in the 
                implementation of these technologies in Africa, a continent with immense potential for renewable energy development.
            </p>
            <p>
                
            </p>
        </div>
        <div class="col-md-4">
            
            <p>
                <img src="cop.png" width ="300"/>       
            </p>
            <p>
                
            </p>
        </div>
        <div class="col-md-4">
            <h2>CARBON FOOTPRINT CALCULATOR</h2>
            <p>
                A Carbon Footprint Calculator is a tool designed to estimate the amount of 
                greenhouse gas emissions generated by an individual, household, organization,
                product, or event over a specified period.
            </p>
            <p>
                <a class="btn btn-default" href="calculator">Learn more &raquo;</a>
            </p>
        </div>
    </div>
</asp:Content>
